//#-hidden-code
//
//  Contents.swift
//
//  Copyright © 2016,2017 Apple Inc. All rights reserved.
//
import UIKit
import PlaygroundSupport

let artView = ArtView(title: "Grid", frame: CGRect(x: 0, y: 0, width: 200, height: 200))
//#-end-hidden-code
/*:
 **Go ahead, run the code now. ▶️**
 This generates an art piece variant.
 Now, **swipe left on the art piece.**
 Keep swiping left to generate more variants.
 You can also go back on a variant by swiping to the right.
 
 Random art pieces need a **seed** to generate randomness, the same seed will always yield the same art variants.
 
 **So go ahead and change the seed below!** Then re-run the code to see the art generated by that seed.
 */
let seed = /*#-editable-code Random seed*/"The iPhone X is top notch!"/*#-end-editable-code*/
let random = Random(seed: seed)
/*:
 This art piece is called: **Square Room**.
 It lays down instances of `SKSpriteNode` in a `Grid` scene and applies different properties like the size, color and shape to each sprite.

 You can play with the properties of the `Grid` class in the code below. Properties left `nil` are randomly determined. If you have any doubt about what a property does, tap on it and select 'Help'. Also, use the autocomplete suggestions to guide you.

 When you are done, go to the next art piece: [Echo](@next).
 */
artView.regenerate = { (i) -> ArtScene in
  
  //#-code-completion(everything, hide)
  // Use this value to fast forwart to a certain art variant.
  let fastForward = /*#-editable-code*/0/*#-end-editable-code*/
  
  let grid = Grid(seed: seed, dropValues: i + fastForward, size: artView.frame.size)

  // Style
  //#-code-completion(identifier, show, chaos, flat, pixel, ., nil)
  grid.style = Grid.Style/*#-editable-code*/.random/*#-end-editable-code*/
  
  // Shapes
  //#-code-completion(everything, show)
  grid.cellImage = Images/*#-editable-code*/.random/*#-end-editable-code*/
  
  // Colors
  grid.colorPalette = Colors/*#-editable-code*/.random/*#-end-editable-code*/
  //#-code-completion(everything, hide)
  //#-code-completion(identifier, hide, .)
  //#-code-completion(literal, show, color)
  grid.cellColor = /*#-editable-code*/nil/*#-end-editable-code*/
  grid.canvasColor = /*#-editable-code*/nil/*#-end-editable-code*/
  
  // Positions
  //#-code-completion(identifier, show, true, false)
  grid.allowFlips = /*#-editable-code*/nil/*#-end-editable-code*/
  grid.allowOffsets = /*#-editable-code*/nil/*#-end-editable-code*/
  
  // Sizes
  //#-code-completion(literal, show, integer)
  grid.cellScale = /*#-editable-code*/nil/*#-end-editable-code*/
  //#-code-completion(identifier, show, true, false)
  grid.allowRandomScale = /*#-editable-code*/nil/*#-end-editable-code*/
  
  // Pattern
  //#-code-completion(literal, show, integer)
  grid.patternComplexity = /*#-editable-code*/nil/*#-end-editable-code*/
  
  // Number of cell divisions
  //#-code-completion(literal, show, integer)
  grid.cellDivision = /*#-editable-code*/nil/*#-end-editable-code*/
  
  return grid
}
//#-hidden-code
PlaygroundPage.current.liveView = artView
//#-end-hidden-code
